import {
    UserOutlined,
    QuestionCircleOutlined,
    InfoCircleOutlined,
    WarningOutlined,
    ClockCircleOutlined,
    StopOutlined,
    DeleteOutlined,
    AreaChartOutlined,
    QqOutlined,
    SketchOutlined,
    FrownOutlined,
    MehOutlined,
    StarOutlined,
    SmileOutlined,
} from '@ant-design/icons';

export const IconsUser = {
    UserOutlined: <UserOutlined />,
    QuestionCircleOutlined: <QuestionCircleOutlined />,
    InfoCircleOutlined: <InfoCircleOutlined />,
    WarningOutlined: <WarningOutlined />,
    ClockCircleOutlined: <ClockCircleOutlined />,
    StopOutlined: <StopOutlined />,
    QqOutlined: <QqOutlined />,
    SketchOutlined: <SketchOutlined />,
    FrownOutlined: <FrownOutlined />,
    MehOutlined: <MehOutlined />,
    StarOutlined: <StarOutlined />,
    SmileOutlined: <SmileOutlined />,
};
